src/Entity/Child.php
<?php

namespace App\Entity;

use App\Repository\ChildRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChildRepository::class)]
class Child
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $first_name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $birth_date = null;

    #[ORM\Column]
    private ?\DateTime $registration_date = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $unsubscription_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $allergy = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $medical_specificity = null;

    /**
     * @var Collection<int, UserChild>
     */
    #[ORM\OneToMany(targetEntity: UserChild::class, mappedBy: 'child')]
    private Collection $userChildren;

    /**
     * @var Collection<int, Planning>
     */
    #[ORM\OneToMany(targetEntity: Planning::class, mappedBy: 'child')]
    private Collection $plannings;



    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $lundi_a = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $lundi_d = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $mardi_a = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $mardi_d = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $mercredi_a = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $mercredi_d = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $jeudi_a = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $jeudi_d = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $vendredi_a = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTime $vendredi_d = null;

    #[ORM\Column(length: 40)]
    private ?string $genre = null;

    /**
     * @var Collection<int, RecoveryChild>
     */
    #[ORM\OneToMany(targetEntity: RecoveryChild::class, mappedBy: 'child')]
    private Collection $recoveryChildren;

    public function __construct()
    {
        $this->userChildren = new ArrayCollection();
        $this->plannings = new ArrayCollection();
        $this->recoveries = new ArrayCollection();
        $this->recoveryChildren = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTime $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTime
    {
        return $this->registration_date;
    }

    public function setRegistrationDate(\DateTime $registration_date): static
    {
        $this->registration_date = $registration_date;

        return $this;
    }

    public function getUnsubscriptionDate(): ?\DateTime
    {
        return $this->unsubscription_date;
    }

    public function setUnsubscriptionDate(?\DateTime $unsubscription_date): static
    {
        $this->unsubscription_date = $unsubscription_date;

        return $this;
    }

    public function getAllergy(): ?string
    {
        return $this->allergy;
    }

    public function setAllergy(?string $allergy): static
    {
        $this->allergy = $allergy;

        return $this;
    }

    public function getMedicalSpecificity(): ?string
    {
        return $this->medical_specificity;
    }

    public function setMedicalSpecificity(?string $medical_specificity): static
    {
        $this->medical_specificity = $medical_specificity;

        return $this;
    }

    /**
     * @return Collection<int, UserChild>
     */
    public function getUserChildren(): Collection
    {
        return $this->userChildren;
    }

    public function addUserChild(UserChild $userChild): static
    {
        if (!$this->userChildren->contains($userChild)) {
            $this->userChildren->add($userChild);
            $userChild->setChild($this);
        }

        return $this;
    }

    public function removeUserChild(UserChild $userChild): static
    {
        if ($this->userChildren->removeElement($userChild)) {
            // set the owning side to null (unless already changed)
            if ($userChild->getChild() === $this) {
                $userChild->setChild(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Planning>
     */
    public function getPlannings(): Collection
    {
        return $this->plannings;
    }

    public function addPlanning(Planning $planning): static
    {
        if (!$this->plannings->contains($planning)) {
            $this->plannings->add($planning);
            $planning->setChild($this);
        }

        return $this;
    }

    public function removePlanning(Planning $planning): static
    {
        if ($this->plannings->removeElement($planning)) {
            // set the owning side to null (unless already changed)
            if ($planning->getChild() === $this) {
                $planning->setChild(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recovery>
     */
    public function getRecoveries(): Collection
    {
        return $this->recoveries;
    }

    public function addRecovery(Recovery $recovery): static
    {
        if (!$this->recoveries->contains($recovery)) {
            $this->recoveries->add($recovery);
            $recovery->addChild($this);
        }

        return $this;
    }

    public function removeRecovery(Recovery $recovery): static
    {
        if ($this->recoveries->removeElement($recovery)) {
            $recovery->removeChild($this);
        }

        return $this;
    }

    public function getLundiA(): ?\DateTime
    {
        return $this->lundi_a;
    }

    public function setLundiA(?\DateTime $lundi_a): static
    {
        $this->lundi_a = $lundi_a;

        return $this;
    }

    public function getLundiD(): ?\DateTime
    {
        return $this->lundi_d;
    }

    public function setLundiD(?\DateTime $lundi_d): static
    {
        $this->lundi_d = $lundi_d;

        return $this;
    }

    public function getMardiA(): ?\DateTime
    {
        return $this->mardi_a;
    }

    public function setMardiA(?\DateTime $mardi_a): static
    {
        $this->mardi_a = $mardi_a;

        return $this;
    }

    public function getMardiD(): ?\DateTime
    {
        return $this->mardi_d;
    }

    public function setMardiD(?\DateTime $mardi_d): static
    {
        $this->mardi_d = $mardi_d;

        return $this;
    }

    public function getMercrediA(): ?\DateTime
    {
        return $this->mercredi_a;
    }

    public function setMercrediA(?\DateTime $mercredi_a): static
    {
        $this->mercredi_a = $mercredi_a;

        return $this;
    }

    public function getMercrediD(): ?\DateTime
    {
        return $this->mercredi_d;
    }

    public function setMercrediD(?\DateTime $mercredi_d): static
    {
        $this->mercredi_d = $mercredi_d;

        return $this;
    }

    public function getJeudiA(): ?\DateTime
    {
        return $this->jeudi_a;
    }

    public function setJeudiA(?\DateTime $jeudi_a): static
    {
        $this->jeudi_a = $jeudi_a;

        return $this;
    }

    public function getJeudiD(): ?\DateTime
    {
        return $this->jeudi_d;
    }

    public function setJeudiD(?\DateTime $jeudi_d): static
    {
        $this->jeudi_d = $jeudi_d;

        return $this;
    }

    public function getVendrediA(): ?\DateTime
    {
        return $this->vendredi_a;
    }

    public function setVendrediA(?\DateTime $vendredi_a): static
    {
        $this->vendredi_a = $vendredi_a;

        return $this;
    }

    public function getVendrediD(): ?\DateTime
    {
        return $this->vendredi_d;
    }

    public function setVendrediD(?\DateTime $vendredi_d): static
    {
        $this->vendredi_d = $vendredi_d;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection<int, RecoveryChild>
     */
    public function getRecoveryChildren(): Collection
    {
        return $this->recoveryChildren;
    }

    public function addRecoveryChild(RecoveryChild $recoveryChild): static
    {
        if (!$this->recoveryChildren->contains($recoveryChild)) {
            $this->recoveryChildren->add($recoveryChild);
            $recoveryChild->setChild($this);
        }

        return $this;
    }

    public function removeRecoveryChild(RecoveryChild $recoveryChild): static
    {
        if ($this->recoveryChildren->removeElement($recoveryChild)) {
            // set the owning side to null (unless already changed)
            if ($recoveryChild->getChild() === $this) {
                $recoveryChild->setChild(null);
            }
        }

src/Controller/ChildController.php
<?php

namespace App\Controller;

use App\Entity\Child;
use App\Form\ChildForm;
use App\Repository\ChildRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/child')]
final class ChildController extends AbstractController
{
    #[Route(name: 'app_child_index', methods: ['GET'])]
    public function index(ChildRepository $childRepository): Response
    {
        return $this->render('child/index.html.twig', [
            'children' => $childRepository->findAll(),
        ]);
    }

    #[Route('/list', name: 'app_child_list', methods: ['GET'])]
    public function list(ChildRepository $childRepository): Response
    {
        return $this->render('child/list.html.twig', [
            'children' => $childRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_child_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $child = new Child();
        $form = $this->createForm(ChildForm::class, $child);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($child);
            $entityManager->flush();

            return $this->redirectToRoute('app_child_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('child/new.html.twig', [
            'child' => $child,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_child_show', methods: ['GET'])]
    public function show(
        Child $child,
        \App\Repository\UserChildRepository $userChildRepository,
        \App\Repository\RecoveryChildRepository $recoveryChildRepository
    ): Response {
        $userChild = $userChildRepository->findOneBy(['child' => $child]);
        $recoveryChild = $recoveryChildRepository->findOneBy(['child' => $child]);
        $recoveryChildren = $recoveryChildRepository->findBy(['child' => $child]);

        return $this->render('child/show.html.twig', [
            'child' => $child,
            'user' => $userChild?->getUser(),
            'userChild' => $userChild,
            'recovery' => $recoveryChild?->getRecovery(),
            'recoveryChild' => $recoveryChild,
            'recoveryChildren' => $recoveryChildren,
            'use_recovery_groups' => false
        ]);
    }

    #[Route('/{id}/edit', name: 'app_child_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Child $child, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChildForm::class, $child);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_child_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('child/edit.html.twig', [
            'child' => $child,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_child_delete', methods: ['POST'])]
    public function delete(Request $request, Child $child, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$child->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($child);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_child_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/profile', name: 'app_child_profile', methods: ['GET'])]
    public function profile(
        Child $child,
        \App\Repository\UserChildRepository $userChildRepository,
        \App\Repository\RecoveryChildRepository $recoveryChildRepository
    ): Response {
        $userChild = $userChildRepository->findOneBy(['child' => $child]);
        $recoveryChild = $recoveryChildRepository->findOneBy(['child' => $child]);
        $recoveryChildren = $recoveryChildRepository->findBy(['child' => $child]);

        return $this->render('child/child_profile.html.twig', [
            'child' => $child,
            'user' => $userChild?->getUser(),
            'userChild' => $userChild,
            'recovery' => $recoveryChild?->getRecovery(),
            'recoveryChild' => $recoveryChild,
            'recoveryChildren' => $recoveryChildren,
        ]);
    }
}

templates/child/_delete_form.html.twig
<form method="post" action="{{ path('app_child_delete', {'id': child.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ child.id) }}">
    <button class="form-button form-button--delete">Delete</button>
</form>

templates/child/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/child/_profile_content.html.twig
{# <pre>
user: {{ dump(user) }}
userChild: {{ dump(userChild) }}
</pre> #}
<div class="recap-wrapper">
    <h1>{{ title|default("Fiche de l'enfant") }}</h1>
    {% if subtitle is defined %}
        <h2>{{ subtitle }}</h2>
    {% endif %}

    <div class="recap-section recap-section--user">
        <div class="section-header">
            <h2>Informations responsable principal</h2>
            {% if show_edit_user %}
                <a href="{{ path('app_inscription_edit_user', {'id': user.id}) }}" class="form-button form-button--edit">
                    <i class="fas fa-edit"></i> Modifier
                </a>
            {% endif %}
        </div>
        {% if userChild is defined and userChild and userChild.user is defined and userChild.user %}
            <div class="section-content section-content--user">
                <p><span>Nom :</span> {{ userChild.user.name }}</p>
                <p><span>Prénom :</span> {{ userChild.user.firstName }}</p>
                <p><span>Email :</span> {{ userChild.user.email }}</p>
                <p><span>Téléphone :</span> {{ userChild.user.phone }}</p>
                <p><span>Lien avec l'enfant :</span> {{ userChild.relation }}</p>
            </div>
        {% else %}
            <div class="section-content section-content--user">
                <p>Aucun responsable principal renseigné.</p>
            </div>
        {% endif %}
    </div>

    {# --- RESPONSABLES LEGAUX ET ACCOMPAGNATEURS --- #}
    {% if use_recovery_groups %}
        {# Encarts responsables légaux #}
        {% set legal_recoveries = recoveryChildren|filter(rc => rc.isResponsable) %}
        {% if legal_recoveries|length > 0 %}
            <div class="recap-section recap-section--user">
                <div class="section-header">
                    <h2>Responsables légaux</h2>
                </div>
                <div class="section-content section-content--user">
                    {% for rc in legal_recoveries %}
                        <p><span>Nom :</span> {{ rc.recovery.name }}</p>
                        <p><span>Prénom :</span> {{ rc.recovery.firstName }}</p>
                        <p><span>Email :</span> {{ rc.recovery.email }}</p>
                        <p><span>Téléphone :</span> {{ rc.recovery.phone }}</p>
                        <p><span>Lien avec l'enfant :</span> {{ rc.relation }}</p>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {# Encarts accompagnateurs simples #}
        {% set simple_recoveries = recoveryChildren|filter(rc => not rc.isResponsable) %}
        {% if simple_recoveries|length > 0 %}
            <div class="recap-section recap-section--user">
                <div class="section-header">
                    <h2>Accompagnateurs autorisés à récupérer l'enfant</h2>
                </div>
                <div class="section-content section-content--user">
                    {% for rc in simple_recoveries %}
                        <div class="section-separation">
                            <p><span>Nom :</span> {{ rc.recovery.name }}</p>
                            <p><span>Prénom :</span> {{ rc.recovery.firstName }}</p>
                            <p><span>Email :</span> {{ rc.recovery.email }}</p>
                            <p><span>Téléphone :</span> {{ rc.recovery.phone }}</p>
                            <p><span>Lien avec l'enfant :</span> {{ rc.relation }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    {% else %}
        {# Affichage classique : premier recoveryChild seulement #}
        {% if recovery and recoveryChild %}
            <div class="recap-section recap-section--user">
                <div class="section-header">
                    <h2>Informations accompagnateur</h2>
                    {% if show_edit_recovery %}
                        <a href="{{ path('app_inscription_edit_recovery', {'id': recovery.id}) }}" class="form-button form-button--edit">
                            <i class="fas fa-edit"></i> Modifier
                        </a>
                    {% endif %}
                </div>
                <div class="section-content section-content--user">
                    <p><span>Nom :</span> {{ recovery.name }}</p>
                    <p><span>Prénom :</span> {{ recovery.firstName }}</p>
                    <p><span>Email :</span> {{ recovery.email }}</p>
                    <p><span>Téléphone :</span> {{ recovery.phone }}</p>
                    <p><span>Lien avec l'enfant :</span> {{ recoveryChild.relation }}</p>
                    <p><span>Responsable légal :</span> {{ recoveryChild.isResponsable ? 'Oui' : 'Non' }}</p>
                </div>
            </div>
        {% endif %}
    {% endif %}

    <div class="recap-section recap-section--child">
        <div class="section-header">
            <h2>Informations enfant</h2>
            {% if show_edit_child %}
                <a href="{{ path('app_inscription_edit_child', {'id': child.id}) }}" class="form-button form-button--edit">
                    <i class="fas fa-edit"></i> Modifier
                </a>
            {% endif %}
        </div>
        <div class="section-content section-content--child">
            <p><span>Nom :</span> {{ child.name }}</p>
            <p><span>Prénom :</span> {{ child.firstName }}</p>
            <p><span>Date de naissance :</span> {{ child.birthDate|date('d/m/Y') }}</p>
            <p><span>Genre :</span> {{ child.genre }}</p>
            <p><span>Allergies :</span> {{ child.allergy ?? 'Aucune' }}</p>
            <p><span>Spécificités médicales :</span> {{ child.medicalSpecificity ?? 'Aucune' }}</p>
        </div>

        <div class="recap-section recap-section--planning">
            <h2>Planning hebdomadaire</h2>
            <div class="planning-grid-recap">
                <div class="grid-header">Jour</div>
                <div class="grid-header">Arrivée</div>
                <div class="grid-header">Départ</div>

                <div class="grid-row grid-row-day">Lundi</div>
                <div class="grid-row">{{ child.lundiA ? child.lundiA|date('H:i') : '-' }}</div>
                <div class="grid-row">{{ child.lundiD ? child.lundiD|date('H:i') : '-' }}</div>

                <div class="grid-row grid-row-day">Mardi</div>
                <div class="grid-row">{{ child.mardiA ? child.mardiA|date('H:i') : '-' }}</div>
                <div class="grid-row">{{ child.mardiD ? child.mardiD|date('H:i') : '-' }}</div>

                <div class="grid-row grid-row-day">Mercredi</div>
                <div class="grid-row">{{ child.mercrediA ? child.mercrediA|date('H:i') : '-' }}</div>
                <div class="grid-row">{{ child.mercrediD ? child.mercrediD|date('H:i') : '-' }}</div>

                <div class="grid-row grid-row-day">Jeudi</div>
                <div class="grid-row">{{ child.jeudiA ? child.jeudiA|date('H:i') : '-' }}</div>
                <div class="grid-row">{{ child.jeudiD ? child.jeudiD|date('H:i') : '-' }}</div>

                <div class="grid-row grid-row-day">Vendredi</div>
                <div class="grid-row">{{ child.vendrediA ? child.vendrediA|date('H:i') : '-' }}</div>
                <div class="grid-row">{{ child.vendrediD ? child.vendrediD|date('H:i') : '-' }}</div>
            </div>
        </div>
    </div>
    {% if show_end_button %}
        <div class="button-group">
            <a href="{{ path('app_administration') }}" class="form-button form-button--submit">Terminer l'inscription</a>
        </div>
    {% endif %}
</div> 

templates/child/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Child index{% endblock %}

{% block body %}
    <h1>Child index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>First_name</th>
                <th>Birth_date</th>
                <th>Genre</th>
                <th>Registration_date</th>
                <th>Unsubscription_date</th>
                <th>Allergy</th>
                <th>Medical_specificity</th>
                <th>Lundi_a</th>
                <th>Lundi_d</th>
                <th>Mardi_a</th>
                <th>Mardi_d</th>
                <th>Mercredi_a</th>
                <th>Mercredi_d</th>
                <th>Jeudi_a</th>
                <th>Jeudi_d</th>
                <th>Vendredi_a</th>
                <th>Vendredi_d</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for child in children %}
            <tr>
                <td>{{ child.id }}</td>
                <td>{{ child.name }}</td>
                
                <td>{{ child.firstName }}</td>
                <td>{{ child.birthDate ? child.birthDate|date('Y-m-d') : '' }}</td>
                <td>{{ child.genre }}</td>
                <td>{{ child.registrationDate ? child.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ child.unsubscriptionDate ? child.unsubscriptionDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ child.allergy }}</td>
                <td>{{ child.medicalSpecificity }}</td>
                <td>{{ child.lundiA ? child.lundiA|date('H:i:s') : '' }}</td>
                <td>{{ child.lundiD ? child.lundiD|date('H:i:s') : '' }}</td>
                <td>{{ child.mardiA ? child.mardiA|date('H:i:s') : '' }}</td>
                <td>{{ child.mardiD ? child.mardiD|date('H:i:s') : '' }}</td>
                <td>{{ child.mercrediA ? child.mercrediA|date('H:i:s') : '' }}</td>
                <td>{{ child.mercrediD ? child.mercrediD|date('H:i:s') : '' }}</td>
                <td>{{ child.jeudiA ? child.jeudiA|date('H:i:s') : '' }}</td>
                <td>{{ child.jeudiD ? child.jeudiD|date('H:i:s') : '' }}</td>
                <td>{{ child.vendrediA ? child.vendrediA|date('H:i:s') : '' }}</td>
                <td>{{ child.vendrediD ? child.vendrediD|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_child_show', {'id': child.id}) }}">show</a>
                    <a href="{{ path('app_child_edit', {'id': child.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="19">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_child_new') }}">Create new</a>
{% endblock %}

templates/child/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Child{% endblock %}

{% block body %}
    <h1>Ajouter un Enfant</h1>

    {{ include('child/_form.html.twig') }}

    <a href="{{ path('app_child_index') }}">back to list</a>
{% endblock %}

templates/child/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Child{% endblock %}

{% block body %}
    <h1>Child</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ child.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ child.name }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ child.firstName }}</td>
            </tr>
            <tr>
                <th>Birth_date</th>
                <td>{{ child.birthDate ? child.birthDate|date('Y-m-d') : '' }}</td>
            </tr>
                        <tr>
                <th>Genre</th>
                <td>{{ child.genre }}</td>
            </tr>
            <tr>
                <th>Registration_date</th>
                <td>{{ child.registrationDate ? child.registrationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Unsubscription_date</th>
                <td>{{ child.unsubscriptionDate ? child.unsubscriptionDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Allergy</th>
                <td>{{ child.allergy }}</td>
            </tr>
            <tr>
                <th>Medical_specificity</th>
                <td>{{ child.medicalSpecificity }}</td>
            </tr>
            <tr>
                <th>Lundi_a</th>
                <td>{{ child.lundiA ? child.lundiA|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Lundi_d</th>
                <td>{{ child.lundiD ? child.lundiD|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mardi_a</th>
                <td>{{ child.mardiA ? child.mardiA|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mardi_d</th>
                <td>{{ child.mardiD ? child.mardiD|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mercredi_a</th>
                <td>{{ child.mercrediA ? child.mercrediA|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Mercredi_d</th>
                <td>{{ child.mercrediD ? child.mercrediD|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Jeudi_a</th>
                <td>{{ child.jeudiA ? child.jeudiA|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Jeudi_d</th>
                <td>{{ child.jeudiD ? child.jeudiD|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Vendredi_a</th>
                <td>{{ child.vendrediA ? child.vendrediA|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Vendredi_d</th>
                <td>{{ child.vendrediD ? child.vendrediD|date('H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_child_index') }}">back to list</a>

    <a href="{{ path('app_child_edit', {'id': child.id}) }}">edit</a>

    {{ include('child/_delete_form.html.twig') }}
{% endblock %}